# Generated by Django 2.0.8 on 2018-11-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_djangostudentrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangostudent',
            name='role',
            field=models.IntegerField(default=6),
        ),
    ]
