# Generated by Django 2.0.8 on 2018-11-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_djangostudent_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangostudentrole',
            name='role',
        ),
    ]
