# Generated by Django 2.0.7 on 2019-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20181111_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(default='plain', max_length=10),
        ),
    ]
