# Generated by Django 2.0.7 on 2019-01-28 21:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20190128_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/chat_uploads'), upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='type',
            new_name='the_type',
        ),
    ]
