# Generated by Django 2.0.7 on 2019-01-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20190128_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatupload',
            name='upload',
            field=models.FileField(upload_to='media/chat_uploads'),
        ),
    ]
