# Generated by Django 2.0.7 on 2019-01-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20190128_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatupload',
            name='upload',
            field=models.FileField(upload_to='chat_uploads'),
        ),
    ]
