# Generated by Django 2.1.2 on 2019-02-25 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20190128_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=250)),
                ('registered_students', models.IntegerField(unique=True)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 26, 0, 21, 49, 293849))),
                ('end_date', models.DateTimeField()),
                ('course_image', models.ImageField(null=True, upload_to='classroom')),
            ],
        ),
    ]
