# Generated by Django 2.1.2 on 2019-02-27 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=300)),
                ('course_video', models.IntegerField()),
                ('registered_students', models.IntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_image', models.ImageField(null=True, upload_to='classroom')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField()),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_video', models.CharField(max_length=100)),
                ('has_notes', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('has_labs', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('topic_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Course')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
