# Generated by Django 2.0.7 on 2019-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_attendancelog_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
