# Generated by Django 2.0.7 on 2020-01-14 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('alternate_graduate_image', models.ImageField(upload_to='')),
                ('graduation_date', models.DateField()),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternate_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.CertificateType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Issue Certificates',
                'verbose_name': 'Issue Certificate',
            },
        ),
    ]
