# Generated by Django 2.0.7 on 2020-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='instructor_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='instructor_signature',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduatecertificates',
            name='alternate_graduate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='graduatecertificates',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
