# Generated by Django 2.0.7 on 2020-03-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20200315_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatecertificates',
            name='alternate_graduate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
