# Generated by Django 2.0.1 on 2018-11-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_detail', models.TextField()),
                ('why_course', models.TextField()),
                ('opportunity', models.TextField()),
                ('prerequisite', models.TextField()),
                ('course_duration', models.PositiveSmallIntegerField()),
                ('study_plan', models.TextField()),
                ('salary', models.IntegerField(default=0)),
                ('salary_source', models.CharField(max_length=200)),
                ('syllabus_content', models.TextField()),
                ('syllabus_topic', models.CharField(max_length=200)),
                ('certificate', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Course')),
            ],
        ),
    ]
