# Generated by Django 2.0.1 on 2018-11-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_coursedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedescription',
            name='syllabus_topic',
        ),
    ]
