# Generated by Django 2.0.1 on 2018-11-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_coursepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepermission',
            old_name='User',
            new_name='user',
        ),
    ]
