# Generated by Django 2.0.1 on 2018-12-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_auto_20181128_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='free',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='has_labs',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='has_notes',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
    ]
