# Generated by Django 2.0.1 on 2018-12-04 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0009_notecomment_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('lab', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Courses.CourseTopic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
