# Generated by Django 2.0.1 on 2018-12-04 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_auto_20181204_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstatus',
            name='total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
