# Generated by Django 2.0.1 on 2018-12-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_topicstatus_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicstatus',
            name='total',
        ),
    ]
