# Generated by Django 2.0.1 on 2018-12-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_auto_20181205_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.Course'),
            preserve_default=False,
        ),
    ]
