# Generated by Django 2.0.1 on 2018-12-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_labtask_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesreport',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.Course'),
            preserve_default=False,
        ),
    ]
