# Generated by Django 2.0.1 on 2018-12-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0016_gradesreport_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradesreport',
            name='course',
        ),
        migrations.RemoveField(
            model_name='labtask',
            name='course',
        ),
    ]
