# Generated by Django 2.0.1 on 2018-12-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0017_auto_20181208_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesreport',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.LabTask'),
            preserve_default=False,
        ),
    ]
