# Generated by Django 2.0.1 on 2018-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0019_coursetopic_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'ordering': ('weight',), 'verbose_name_plural': 'Course Topics'},
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='weight',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
