# Generated by Django 2.0.1 on 2018-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0020_auto_20181217_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('weight',), 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursetopic',
            options={'verbose_name_plural': 'Course Topics'},
        ),
        migrations.RemoveField(
            model_name='coursetopic',
            name='weight',
        ),
        migrations.AddField(
            model_name='course',
            name='weight',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
