# Generated by Django 2.0.1 on 2018-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0022_course_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
