# Generated by Django 2.0.7 on 2019-02-16 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0024_coursetopic_lab_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepermission',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
