# Generated by Django 2.0.7 on 2019-03-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0026_usercoursestat_userinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterest',
            options={'ordering': ('user', 'course')},
        ),
    ]
