# Generated by Django 2.0.7 on 2019-04-02 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0027_auto_20190302_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursestat',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
