# Generated by Django 2.0.7 on 2019-04-13 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0029_auto_20190413_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstatus',
            name='start_video',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='stop_video',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
