# Generated by Django 2.0.7 on 2019-04-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0030_auto_20190413_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicstatus',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='start_video',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='stop_video',
        ),
    ]
