# Generated by Django 2.0.7 on 2019-04-25 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0031_auto_20190425_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstatus',
            name='status',
            field=models.CharField(default='start_video', max_length=200),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='video',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
