# Generated by Django 2.0.7 on 2019-04-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0032_auto_20190425_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicstatus',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='TopicStatus',
        ),
    ]
