# Generated by Django 2.0.7 on 2019-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0034_topicstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_certification',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
