# Generated by Django 2.0.7 on 2020-04-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0038_coursetopic_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='duration',
            field=models.IntegerField(default=55),
        ),
    ]
