# Generated by Django 2.0.7 on 2020-06-07 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0039_auto_20200417_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradesReportsReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('receivers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='permissions')),
            ],
        ),
    ]
