# Generated by Django 2.0.7 on 2020-06-07 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0040_gradesreportsreceiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesreportsreceiver',
            name='receivers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='receivers'),
        ),
    ]
