# Generated by Django 2.0.7 on 2020-06-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0041_auto_20200607_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesreportsreceiver',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.Course'),
        ),
    ]
