"""
Django settings for Linuxjobber project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os, sys, datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from decouple import config, Csv

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'y@my*7-t9p1rzf&2ryw*m+@1w-*-e5d=)5l_9)5ibtw7v7#2z_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', True,cast=bool)

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    'rest_framework',
    'channels',
    # 'ckeditor',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'home.apps.HomeConfig',
    'Courses.apps.CoursesConfig',
    'Projects.apps.ProjectsConfig',
    'ToolsApp.apps.ToolsappConfig',
    'classroom.apps.ClassroomConfig',
    'rest_framework.authtoken',
    'sso_api',
    'storages',
    'livereload',
    'background_task',
    'certificates',

    'awswebsocket'
]

CORS_ORIGIN_ALLOW_ALL = True

# Default permission that allows anyone to access our API. This is left this way for development purpose it should be changed before it gets to production.

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

JWT_AUTH = {
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'classroom.views.jwt_response_payload_handler',
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=24),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'home.middleware.SessionMiddle.SessionMiddleWare',
'livereload.middleware.LiveReloadScript',
]

ROOT_URLCONF = 'Linuxjobber.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.courses',
                'home.context_processors.tools',
                'home.context_processors.workexperience',
            ],
        },
    },
]

WSGI_APPLICATION = 'Linuxjobber.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# Todo Before Push modify to original credentials
# Here I made use of a mysql database for expense application
DATABASES = {
    'default': {
        'ENGINE': config('DATABASE_ENGINE', 'django.db.backends.mysql'), 
        'NAME': config('DATABASE_NAME', 'linuxjobber'),  # linuxjb
        'USER': config('DATABASE_USER', 'root'),  # linuxjobber
        'PASSWORD': config('DATABASE_PASSWORD', 'samjam1989'),  # linuxjobber
        'HOST': config('DATABASE_HOST', 'localhost'),
        'PORT': config('DATABASE_PORT', ''),

    }


} 

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%y-%m-%d %H:%M:%S'
        },

        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },

    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },

        'development_logfile': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_dev.log'),
            'formatter': 'verbose'
        },

        'production_logfile': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'django_production.log'),
            'maxBytes': 1024 * 1024 * 100,
            'backupCount': 5,
            'formatter': 'simple'
        },

        'dba_logfile': {
            'level': 'DEBUG',
            'filters': ['require_debug_false', 'require_debug_true'],
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': os.path.join(BASE_DIR, 'django_dba.log'),
            'formatter': 'simple'
        },
    },

    'root': {
        'level': 'DEBUG',
        'handlers': ['console'],
    },

    'loggers': {
        'livelinuxjobber': {
            'handlers': ['development_logfile', 'production_logfile'],
        },

        'dba': {
            'handlers': ['dba_logfile'],
        },

        'django': {
            'handlers': ['development_logfile', 'production_logfile'],
        },

        'py.warnings': {
            'handlers': ['development_logfile'],
        },
    }
}

# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)

AWS_DEFAULT_ACL = None
AWS_DEFAULT_ACL = config('AWS_DEFAULT_ACL',None)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', '')
S3DIRECT_REGION = config('S3DIRECT_REGION','us-west-2')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', '')
AWS_QUERYSTRING_AUTH = False #This will make sure that the file URL does not have unnecessary parameters like your access key.
AWS_S3_CUSTOM_DOMAIN = AWS_STORAGE_BUCKET_NAME + '.s3.amazonaws.com'
# AWS_S3_CUSTOM_DOMAIN = 's3.amazonaws.com/'+AWS_STORAGE_BUCKET_NAME


# Static media settings
AWS_LOCATION = config('AWS_LOCATION','static')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = "/mnt/media/"
STATIC_ROOT = "/mnt/asset/"
DEFAULT_FILE_STORAGE = config('DEFAULT_FILE_STORAGE','home.storage_backend.S3UploadStorage')
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'asset'),
    os.path.join(BASE_DIR, 'static'),
]

if not DEBUG:
    MEDIA_URL = 'http://' + AWS_STORAGE_BUCKET_NAME + '.s3.amazonaws.com/media/'
    # MEDIA_URL = "https://s3.amazonaws.com/" + AWS_STORAGE_BUCKET_NAME + '/media/'
    # STATIC_URL = 'http://' + AWS_STORAGE_BUCKET_NAME + '.s3.amazonaws.com/{}/'.format(AWS_LOCATION)

STATICFILES_FINDERS = (
'django.contrib.staticfiles.finders.FileSystemFinder',
'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)


# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
ENV_URL = config('ENV_URL',"http://127.0.0.1:8000/")


EMAIL_BACKEND = "home.mail_service.CustomEmailBackend"
EMAIL_HOST = config('EMAIL_HOST', 'smtp.linuxjobber.com')
EMAIL_PORT = config('EMAIL_PORT', '587')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', 'admin@linuxjobber.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', 'm4k3Aw!y')
EMAIL_USE_TLS = True



STRIPE_PUBLIC_KEY = "pk_test_1zBTca83q29gl9iwRw1oIBvD"
STRIPE_SECRET_KEY = "Something"
AUTH_USER_MODEL = 'users.CustomUser'




# Channels
ASGI_APPLICATION = 'Linuxjobber.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('channel_hosts', default="127.0.0.1,6379", cast=Csv(post_process=tuple))],
        },
    },
}

# todo Always change to appropriate before pushing
# SERVER details
SERVER_IP = config('SERVER_IP', "192.168.122.1")
SERVER_USER = config('SERVER_USER', "sysadmin")
SERVER_PASSWORD = config('SERVER_PASSWORD', "8iu7*IU&")
GROUP_CLASS_URL = config('GROUP_CLASS_URL', 'http://localhost:4200/classroom/')
FASMAIL_URL = config('GROUP_CLASS_URL', 'http://localhost:4300/')

TOOLS_USER = config('TOOLS_USER', "samuel")
TOOLS_PASSWORD = config('TOOLS_PASSWORD', "8iu7*IU&")
OLD_TOOLS_PATH = config('OLD_TOOLS_PATH', "/oldtools/campaigns/")
NEW_TOOLS_PATH = config('NEW_TOOLS_PATH', "/tools/campaigns/")


SESSION_EXPIRE_AT_BROWSER_CLOSE = True
 
AWS_WS_GATEWAY = config('AWS_WS_GATEWAY','url')

SES_EMAIL = config('SES_EMAIL','no@test.com')


AWS_ACCESS_KEY_ID_WEBSOCKET = config('AWS_ACCESS_KEY_ID_WEBSOCKET', AWS_ACCESS_KEY_ID)
AWS_SECRET_ACCESS_KEY_WEBSOCKET = config('AWS_ACCESS_KEY_ID_WEBSOCKET', AWS_SECRET_ACCESS_KEY)