# Generated by Django 2.0.1 on 2018-11-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_monthlysubscriptionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlySubscriptionPlan',
        ),
    ]
