# Generated by Django 2.0.1 on 2018-11-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_billinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='subscription_id',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
