# Generated by Django 2.0.1 on 2018-11-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181109_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysubscriber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='action',
        ),
        migrations.DeleteModel(
            name='MonthlySubscriber',
        ),
    ]
