# Generated by Django 2.1.2 on 2018-11-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181109_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
