# Generated by Django 2.0.1 on 2018-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181109_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretkey', models.TextField()),
                ('publickey', models.TextField()),
                ('planid', models.TextField()),
            ],
        ),
    ]
