# Generated by Django 2.0.7 on 2018-11-27 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0001_initial'),
        ('home', '0009_newslettersubscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.Course'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
