# Generated by Django 2.0.1 on 2018-11-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_newslettersubscribers'),
        ('home', '0009_stripepayment'),
    ]

    operations = [
    ]
