# Generated by Django 2.0.1 on 2018-11-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181127_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
