# Generated by Django 2.0.1 on 2018-11-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_location_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zipcode',
        ),
    ]
