# Generated by Django 2.0.7 on 2018-12-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       ('home', '0014_remove_location_zipcode'),
        ('home', '0010_auto_20181128_0031'),
    ]

    operations = [
    ]
