# Generated by Django 2.1.2 on 2018-12-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_location_zipcode'),
        ('home', '0010_rhcsaorder'),
    ]

    operations = [
    ]
