# Generated by Django 2.0.7 on 2018-12-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20181203_1214'),
        ('home', '0015_merge_20181203_1037'),
    ]

    operations = [
    ]
