# Generated by Django 2.0.7 on 2019-01-02 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_merge_20181215_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='wepeoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_position', models.CharField(max_length=20)),
                ('current_position', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
                ('relocation', models.CharField(max_length=1)),
                ('last_verification', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('graduation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('person_type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
