# Generated by Django 2.0.7 on 2019-01-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190103_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='relocation',
            field=models.CharField(max_length=5),
        ),
    ]
