# Generated by Django 2.0.7 on 2019-01-03 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190103_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='current_position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='income',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='person_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='relocation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='trainee_position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
