# Generated by Django 2.0.7 on 2019-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190103_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('cv', models.FileField(upload_to='resume')),
                ('position', models.IntegerField(choices=[(1, 'Part-time Frontend Developer'), (2, 'Web Frontend Developer')], default=1)),
                ('high_salary', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='high_salary',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
