# Generated by Django 2.0.7 on 2019-01-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20190116_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttimejob',
            name='cv_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
