# Generated by Django 2.0.7 on 2019-01-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_parttimejob_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimejob',
            name='cv',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
