# Generated by Django 2.0.7 on 2019-01-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190116_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTimePostion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('requirement', models.CharField(max_length=200)),
                ('responsibility', models.TextField()),
                ('weight', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTimePostion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PartTimePostion'),
        ),
    ]
