# Generated by Django 2.0.7 on 2019-01-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190119_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FullTimePostion'),
        ),
    ]
