# Generated by Django 2.0.7 on 2019-01-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190119_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='high_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='cv_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
