# Generated by Django 2.0.7 on 2019-01-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190119_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='job',
            name='lastname',
        ),
    ]
