# Generated by Django 2.0.7 on 2019-01-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190119_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wepeoples',
            name='user',
        ),
        migrations.DeleteModel(
            name='wepeoples',
        ),
    ]
