# Generated by Django 2.0.7 on 2019-01-27 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_auto_20190127_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='wepeoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='resume')),
                ('trainee_position', models.CharField(max_length=20, null=True)),
                ('current_position', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('income', models.CharField(max_length=20, null=True)),
                ('relocation', models.CharField(max_length=5, null=True)),
                ('Paystub', models.ImageField(null=True, upload_to='resume')),
                ('last_verification', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('graduation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wepeoples',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wetype'),
        ),
        migrations.AddField(
            model_name='wepeoples',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
