# Generated by Django 2.0.7 on 2019-01-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_wetask_wework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wepeoples',
            old_name='trainee_position',
            new_name='person_type',
        ),
    ]
