# Generated by Django 2.0.7 on 2019-01-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190128_1309'),
        ('home', '0030_groupclasslog'),
    ]

    operations = [
    ]
