# Generated by Django 2.0.7 on 2019-02-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20190210_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='wetask',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
