# Generated by Django 2.0.7 on 2019-03-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
