# Generated by Django 2.0.7 on 2019-03-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_unsubscriber'),
        ('home', '0044_groupclass_video_required'),
    ]

    operations = [
    ]
