# Generated by Django 2.0.7 on 2019-03-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_merge_20190318_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
