# Generated by Django 2.0.7 on 2019-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_message_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='werole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wepeoples',
            name='person_type',
        ),
    ]
