# Generated by Django 2.0.7 on 2019-05-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_wepeoples_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='paid_date',
        ),
    ]
