# Generated by Django 2.0.7 on 2019-05-07 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_userorder_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
