# Generated by Django 2.0.7 on 2019-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20190510_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='subscription',
            field=models.CharField(max_length=50),
        ),
    ]
