# Generated by Django 2.0.7 on 2019-06-24 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20190515_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
