# Generated by Django 2.0.7 on 2019-05-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20190507_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
