# Generated by Django 2.2.2 on 2019-06-29 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_internship_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target', models.PositiveSmallIntegerField(choices=[(0, 'all role 6'), (1, 'all role 4'), (2, 'Nigerian Interns'), (3, 'Parttime Fresh Graduate'), (4, 'Marketing Internship')], default=1)),
                ('send_message', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Message')),
            ],
        ),
    ]
