# Generated by Django 2.2.2 on 2019-07-12 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeAccountClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('from_what_page', models.CharField(blank=True, max_length=100)),
                ('registered', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('visited_tryfree', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('paid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
