# Generated by Django 2.2.2 on 2019-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_freeaccountclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeaccountclick',
            name='filled_jobs',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='freeaccountclick',
            name='freeaccountclick',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='freeaccountclick',
            name='tryfreeclick',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
