# Generated by Django 2.0.7 on 2019-07-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20190712_0004'),
        ('home', '0058_freeaccountclick'),
    ]

    operations = [
    ]
