# Generated by Django 2.0.7 on 2019-07-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_merge_20190727_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
