# Generated by Django 2.1.7 on 2019-08-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20190721_1715'),
        ('home', '0060_auto_20190727_0928'),
    ]

    operations = [
    ]
