# Generated by Django 2.0.7 on 2019-09-09 13:42

from django.db import migrations, models
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_merge_20190806_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wework',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wework',
            name='due',
            field=models.DateTimeField(default=home.models.due_time),
        ),
    ]
