# Generated by Django 2.0.7 on 2019-09-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_careerswitchapplication'),
        ('home', '0062_auto_20190909_1342'),
    ]

    operations = [
    ]
