# Generated by Django 2.0.7 on 2019-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20190920_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltimepostion',
            name='requirement',
            field=models.CharField(max_length=500),
        ),
    ]
