# Generated by Django 2.0.7 on 2019-09-21 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0036_auto_20190727_0928'),
        ('home', '0068_job_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Courses.Course'),
        ),
    ]
