# Generated by Django 2.0.7 on 2019-09-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auto_20190921_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltimepostion',
            name='interested_page',
            field=models.CharField(default='home:userinterest', max_length=500),
        ),
        migrations.AlterField(
            model_name='fulltimepostion',
            name='not_interested_page',
            field=models.CharField(default='home:jobfeed', max_length=500),
        ),
        migrations.AlterField(
            model_name='fulltimepostion',
            name='skilled_page',
            field=models.CharField(default='home:workexperience', max_length=500),
        ),
    ]
