# Generated by Django 2.0.7 on 2019-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20190921_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_id', models.CharField(max_length=200, unique=True)),
                ('graduate_name', models.CharField(max_length=250)),
                ('graduate_email', models.CharField(max_length=200)),
                ('graduation_date', models.CharField(max_length=200)),
                ('technology_learnt', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
