# Generated by Django 2.0.7 on 2019-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='response',
            field=models.CharField(max_length=5000),
        ),
    ]
