# Generated by Django 2.0.7 on 2019-10-02 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerswitchapplication',
            name='application_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='application_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parttimejob',
            name='application_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
