# Generated by Django 2.0.7 on 2019-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_faq_is_wefaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=2000),
        ),
    ]
