# Generated by Django 2.0.7 on 2019-10-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_auto_20191002_1339'),
        ('home', '0077_faq_is_fifty_percent_faq'),
    ]

    operations = [
    ]
