# Generated by Django 2.0.7 on 2019-10-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_merge_20191008_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
