# Generated by Django 2.0.7 on 2019-10-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20191016_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='application_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
