# Generated by Django 2.0.7 on 2019-10-16 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_auto_20191016_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerswitchapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
