# Generated by Django 2.0.7 on 2019-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_auto_20191110_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessagelog',
            name='header_text',
            field=models.CharField(default='Linuxjobber', max_length=255),
        ),
    ]
