# Generated by Django 2.2.2 on 2019-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20191113_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeclass',
            name='show_on_footer',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
    ]
