# Generated by Django 2.0.7 on 2019-11-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_emailmessagelog_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessagelog',
            name='message_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.EmailMessageType'),
        ),
    ]
