# Generated by Django 2.2.2 on 2019-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_completeclass_show_on_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeclass',
            name='name',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
