# Generated by Django 2.0.7 on 2019-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_auto_20191110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessagelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
