# Generated by Django 2.0.7 on 2019-11-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_completeclass_name'),
        ('home', '0085_auto_20191110_1134'),
    ]

    operations = [
    ]
