# Generated by Django 2.2.2 on 2019-11-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_merge_20191126_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeclass',
            name='rating_point',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='completeclass',
            name='rating_total',
            field=models.CharField(default='2673', max_length=200),
        ),
    ]
