# Generated by Django 2.2.2 on 2019-12-08 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0087_auto_20191128_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='workexppay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('job_placement', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='workexpisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Annual_Income', models.TextField(null=True)),
                ('Monthly_House_Payment', models.TextField(null=True)),
                ('Highest_level_education', models.TextField(null=True)),
                ('Employment_status', models.TextField(null=True)),
                ('Estimated_date_of_program_completion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Signed_isa', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='workexpeligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('middle_initial', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('address', models.TextField()),
                ('apt_number', models.TextField()),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('SSN', models.TextField()),
                ('employee_address', models.TextField()),
                ('employee_email', models.TextField()),
                ('employee_phone', models.CharField(max_length=50, null=True)),
                ('preparer_or_translator', models.IntegerField(choices=[(0, 'I do not user a preparer or translator'), (1, 'A preparer or translator assisted the employee in completing section 1')], default=0)),
                ('i_am_a', models.IntegerField(choices=[(0, 'A citizen of the united states'), (1, 'A non national citizen of the united states'), (3, 'A lawful permanent resident'), (4, 'An alien authorized to work')], default=0)),
                ('Alien_reg_num', models.TextField(null=True)),
                ('form_19_num', models.TextField(null=True)),
                ('foreign_pass_num', models.TextField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
