# Generated by Django 2.0.7 on 2019-12-05 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_auto_20191204_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='payments',
        ),
        migrations.AddField(
            model_name='subpayment',
            name='installment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.InstallmentPlan'),
        ),
    ]
