# Generated by Django 2.2.2 on 2019-12-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_workexpeligibility_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexpisa',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
