# Generated by Django 2.0.7 on 2019-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_auto_20191205_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='status',
            field=models.CharField(default='is_unpaid', editable=False, max_length=15),
        ),
    ]
