# Generated by Django 2.0.7 on 2019-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_installmentplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpayment',
            name='paid_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
