# Generated by Django 2.0.7 on 2019-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_subpayment_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpayment',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
