# Generated by Django 2.2.2 on 2019-12-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_subpayment_paid_on'),
        ('home', '0090_workexpisa_email'),
    ]

    operations = [
    ]
