# Generated by Django 2.2.2 on 2019-12-11 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0092_merge_20191210_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperienceIsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('Current_Annual_Income', models.TextField(null=True)),
                ('Monthly_House_Payment', models.TextField(null=True)),
                ('Highest_level_education', models.TextField(null=True)),
                ('Employment_status', models.TextField(null=True)),
                ('Estimated_date_of_program_completion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_Signed_isa', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='workexpeligibility',
            new_name='WorkExperienceEligibility',
        ),
        migrations.RenameModel(
            old_name='workexppay',
            new_name='WorkExperiencePay',
        ),
        migrations.DeleteModel(
            name='workexpisa',
        ),
    ]
