# Generated by Django 2.2.2 on 2019-12-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20191211_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiencepay',
            name='paid',
        ),
        migrations.AddField(
            model_name='workexperiencepay',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='i_am_a',
            field=models.IntegerField(choices=[(0, 'A citizen of the united states'), (1, 'A non national citizen of the united states'), (2, 'A lawful permanent resident'), (3, 'An alien authorized to work')], default=0),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='preparer_or_translator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workexperienceisa',
            name='is_Signed_isa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workexperiencepay',
            name='job_placement',
            field=models.BooleanField(default=False),
        ),
    ]
