# Generated by Django 2.2.2 on 2019-12-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_auto_20191211_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperiencepay',
            old_name='job_placement',
            new_name='includes_job_placement',
        ),
    ]
