# Generated by Django 2.2.2 on 2019-12-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_auto_20191211_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperienceisa',
            old_name='current_annual_Income',
            new_name='current_annual_income',
        ),
        migrations.RenameField(
            model_name='workexperienceisa',
            old_name='monthly_house_Payment',
            new_name='monthly_house_payment',
        ),
    ]
