# Generated by Django 2.0.7 on 2019-12-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_subpayment_is_disabled'),
        ('home', '0097_auto_20191211_1425'),
    ]

    operations = [
    ]
