# Generated by Django 2.0.7 on 2019-12-14 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0099_emailgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroupMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_instant', models.BooleanField(default=True)),
                ('delivery_time', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Send Message',
                'verbose_name_plural': 'Send Message',
            },
        ),
        migrations.RemoveField(
            model_name='emailgroup',
            name='members_by_role',
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='exclude_clause',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='sql_query',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailgroup',
            name='where_clause',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailmessagelog',
            name='group_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.EmailGroup'),
        ),
        migrations.AddField(
            model_name='emailgroupmessagelog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.EmailGroup'),
        ),
    ]
