# Generated by Django 2.2.2 on 2019-12-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_workexperiencepricewaiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencepricewaiver',
            name='price',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
