# Generated by Django 2.0.7 on 2019-12-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_auto_20191214_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailgroupmessagelog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='emailgroupmessagelog',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailgroupmessagelog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Message'),
        ),
        migrations.AlterField(
            model_name='emailmessagelog',
            name='group_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.EmailGroupMessageLog'),
        ),
    ]
