# Generated by Django 2.0.7 on 2019-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_auto_20191215_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroupmessagelog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
