# Generated by Django 2.0.7 on 2019-12-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_auto_20191215_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
