# Generated by Django 2.2.2 on 2019-12-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_installmentplan_is_cancelled'),
        ('home', '0101_auto_20191220_0635'),
    ]

    operations = [
    ]
