# Generated by Django 2.0.7 on 2020-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_variables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variables',
            options={'verbose_name': 'Variables', 'verbose_name_plural': 'Variables'},
        ),
        migrations.AddField(
            model_name='workexperienceeligibility',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperienceeligibility',
            name='ssn_first_six',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperienceeligibility',
            name='ssn_last_four',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
