# Generated by Django 2.0.7 on 2020-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_auto_20200105_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='ssn_first_six',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='ssn_last_four',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
