# Generated by Django 2.0.7 on 2020-01-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0110_auto_20200105_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperienceeligibility',
            old_name='ssn_first_six',
            new_name='ssn_first_five',
        ),
    ]
