# Generated by Django 2.0.7 on 2020-01-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_auto_20200105_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItPartnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('idea_title', models.CharField(max_length=500)),
                ('idea_detail', models.TextField()),
            ],
        ),
    ]
