# Generated by Django 2.0.7 on 2020-01-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_auto_20200126_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperienceeligibility',
            name='terms',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
