# Generated by Django 2.0.7 on 2020-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_workexperienceeligibility_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='pdf',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='terms',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='workexperienceisa',
            name='pdf',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
