# Generated by Django 2.0.7 on 2020-01-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_auto_20200121_0130'),
        ('home', '0114_auto_20200128_1011'),
    ]

    operations = [
    ]
