# Generated by Django 2.0.7 on 2020-02-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_auto_20200213_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperienceeligibility',
            name='generate_pdf',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='workexperienceisa',
            name='generate_pdf',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
