# Generated by Django 2.0.7 on 2020-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_auto_20200214_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='Alien_reg_num',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='foreign_pass_num',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='form_19_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
