# Generated by Django 2.0.7 on 2020-02-16 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_auto_20200216_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
