# Generated by Django 2.0.7 on 2020-02-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_auto_20200216_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='terms',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
