# Generated by Django 2.0.7 on 2020-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_auto_20200216_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
