# Generated by Django 2.0.7 on 2020-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_auto_20200216_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='wetask',
            name='video_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wework',
            name='video_status',
            field=models.IntegerField(choices=[(0, 'Not Watched'), (1, 'Grading'), (2, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='wework',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not done'), (1, 'Grading'), (2, 'Failed'), (3, 'Completed')], default=0),
        ),
    ]
