# Generated by Django 2.0.7 on 2020-03-19 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0126_auto_20200316_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperiencePaystub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystub', models.ImageField(null=True, upload_to='resume')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wepeoples',
            name='Paystub',
        ),
        migrations.AlterField(
            model_name='wework',
            name='video_status',
            field=models.IntegerField(choices=[(0, 'Not Watched'), (1, 'Watching'), (2, 'Completed')], default=0),
        ),
    ]
