# Generated by Django 2.0.7 on 2020-03-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0127_auto_20200319_1047'),
        ('home', '0125_groupclass_image'),
    ]

    operations = [
    ]
