# Generated by Django 2.0.7 on 2020-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_workexpformstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='person',
            field=models.CharField(choices=[('TR', 'Trainee'), ('ST', 'Student')], default='TR', max_length=2, null=True),
        ),
    ]
