# Generated by Django 2.0.7 on 2020-04-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_auto_20200330_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='wework',
            name='trainee_stat',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Stopped', 'Stopped'), ('Extended', 'Extended'), ('Ready-state', 'Ready-state'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
