# Generated by Django 2.0.7 on 2020-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0130_auto_20200328_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='person',
            field=models.CharField(choices=[('TR', 'Trainee'), ('ST', 'Student')], default='TR', max_length=20, null=True),
        ),
    ]
