# Generated by Django 2.0.7 on 2020-03-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_auto_20200328_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='person',
            field=models.PositiveIntegerField(choices=[(1, 'Trainee'), (2, 'Student')], default=1, max_length=20, null=True),
        ),
    ]
