# Generated by Django 2.0.7 on 2020-04-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_auto_20200403_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='wetraineestatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.wepeoples'),
        ),
    ]
