# Generated by Django 2.0.7 on 2020-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0132_auto_20200328_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='person',
            field=models.IntegerField(choices=[(0, 'Trainee'), (1, 'Student')], default=0, max_length=20, null=True),
        ),
    ]
