# Generated by Django 2.0.7 on 2020-04-11 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0132_wetraineestatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='resume',
            field=models.FileField(upload_to='uploads/resume'),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/resume'),
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='cv',
            field=models.FileField(null=True, upload_to='uploads/resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(upload_to='uploads/resume'),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/I-9/'),
        ),
        migrations.AlterField(
            model_name='workexperienceeligibility',
            name='terms',
            field=models.FileField(blank=True, null=True, upload_to='uploads/I-9/'),
        ),
        migrations.AlterField(
            model_name='workexperienceisa',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ISA'),
        ),
        migrations.AlterField(
            model_name='workexperiencepaystub',
            name='paystub',
            field=models.ImageField(null=True, upload_to='uploads/paystubs'),
        ),
    ]
