# Generated by Django 2.0.7 on 2020-04-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_auto_20200411_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordWEChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
