# Generated by Django 2.0.7 on 2020-03-28 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0134_auto_20200328_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wepeoples',
            name='current_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='graduation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='income',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='last_verification',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='person',
            field=models.IntegerField(blank=True, choices=[(0, 'Trainee'), (1, 'Student')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='relocation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wepeoples',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.wetype'),
        ),
    ]
