# Generated by Django 2.0.7 on 2020-04-17 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0134_recordwechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordwechange',
            name='change_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.wepeoples'),
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='new_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='prev_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='userid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
