# Generated by Django 2.0.7 on 2020-04-19 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_auto_20200417_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordwechange',
            old_name='new_value',
            new_name='change_type',
        ),
        migrations.RenameField(
            model_name='recordwechange',
            old_name='prev_value',
            new_name='new_info',
        ),
        migrations.RemoveField(
            model_name='recordwechange',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='recordwechange',
            name='field',
        ),
        migrations.RemoveField(
            model_name='recordwechange',
            name='userid',
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='change_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='recordwechange',
            name='old_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
