# Generated by Django 2.0.7 on 2020-04-22 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0136_auto_20200419_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=100)),
                ('satisfaction', models.CharField(choices=[('1', 'Least Satisfied'), ('2', 'Not Satisfied'), ('3', 'Somewhat Satisfied'), ('4', 'Satisfied'), ('5', 'Very Satisfied')], max_length=50)),
                ('recommend_us', models.CharField(choices=[('1', 'Least Likely'), ('2', 'Not Likely'), ('3', 'Somewhat Likely'), ('4', 'Likely'), ('5', 'Very Likely')], max_length=50)),
                ('has_friend', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
