# Generated by Django 2.0.7 on 2020-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0137_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='has_friend',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=10),
        ),
    ]
