# Generated by Django 2.0.7 on 2020-05-13 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0140_auto_20200513_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentHistory',
            new_name='BillingHistory',
        ),
    ]
