# Generated by Django 2.0.7 on 2020-05-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0140_auto_20200514_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.wepeoples'),
        ),
    ]
