# Generated by Django 2.0.7 on 2020-05-18 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0141_auto_20200514_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='course_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
