# Generated by Django 2.0.7 on 2020-05-20 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0142_groupclass_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='deleted',
            field=models.ManyToManyField(blank=True, related_name='deleted_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
