# Generated by Django 2.0.7 on 2020-05-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0143_groupclass_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billinghistory',
            table='home_paymenthistory',
        ),
    ]
