# Generated by Django 2.0.7 on 2020-06-12 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0144_auto_20200526_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(blank=True, max_length=200, null=True)),
                ('internship', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
