# Generated by Django 2.0.7 on 2020-05-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0144_auto_20200525_1937'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billinghistory',
            table='home_billinghistory',
        ),
    ]
