# Generated by Django 2.0.7 on 2020-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0145_internshipdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipdetails',
            name='for_enquiries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipdetails',
            name='form_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
