# Generated by Django 2.0.1 on 2018-11-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('task', models.TextField()),
                ('xpected', models.TextField(default='Nil')),
                ('hint', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Lab Tasks',
                'ordering': ('lab_id', 'task_number'),
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='ToolTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.CharField(max_length=200)),
                ('lab_name', models.CharField(max_length=50)),
                ('video', models.TextField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_app_topics', related_query_name='tools_app_topic', to='ToolsApp.Tool')),
            ],
            options={
                'verbose_name_plural': 'Tool Topics',
            },
        ),
        migrations.AddField(
            model_name='labtask',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_app_tasks', related_query_name='tools_app_task', to='ToolsApp.ToolTopic'),
        ),
    ]
