# Generated by Django 2.1.2 on 2019-02-11 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('lab_task_no', models.IntegerField(default=1)),
                ('task', models.TextField()),
                ('task_note', models.TextField()),
                ('task_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=500)),
                ('project_image', models.TextField(max_length=500)),
                ('project_bg_image', models.TextField(max_length=500)),
                ('project_contents', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=500)),
                ('course_objective', models.CharField(max_length=100)),
                ('course_content', models.CharField(max_length=500)),
                ('course_duration', models.CharField(max_length=20)),
                ('course_image', models.TextField(max_length=1000)),
                ('lab_submission_type', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'submit by uploading document'), (2, 'submit by machine ID'), (3, 'submit from repo')], default=1)),
                ('course_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Projects Course',
            },
        ),
        migrations.CreateModel(
            name='ProjectCourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(unique=True)),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourse')),
            ],
            options={
                'verbose_name_plural': 'Projects Course Topic',
            },
        ),
        migrations.CreateModel(
            name='UsersLabTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.LabTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='labtask',
            name='lab_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourseTopic'),
        ),
    ]
