# Generated by Django 2.1.2 on 2019-02-14 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.IntegerField(unique=True)),
                ('lab_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('lab_task_no', models.IntegerField(default=1)),
                ('task', models.TextField()),
                ('task_note', models.TextField()),
                ('task_comment', models.TextField()),
                ('task_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.CourseLab')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopicNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(unique=True)),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=500)),
                ('project_image', models.ImageField(null=True, upload_to='project')),
                ('project_contents', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('project_id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=250)),
                ('course_objective', models.CharField(max_length=100)),
                ('course_content', models.CharField(max_length=250)),
                ('course_duration', models.CharField(max_length=20)),
                ('course_image', models.ImageField(null=True, upload_to='project')),
                ('lab_submission_type', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'submit by uploading document'), (2, 'submit by machine ID'), (3, 'submit from repo')], default=1)),
                ('course_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Projects Course',
            },
        ),
        migrations.CreateModel(
            name='ProjectCourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField()),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_video', models.CharField(max_length=100)),
                ('has_notes', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('has_labs', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('topic_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourse')),
            ],
            options={
                'verbose_name_plural': 'Projects Course Topic',
            },
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourse')),
                ('user', models.ForeignKey(limit_choices_to={'role': 4}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersLabTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.CourseLabTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coursetopicnote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourseTopic'),
        ),
        migrations.AddField(
            model_name='courselab',
            name='lab_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourse'),
        ),
        migrations.AlterUniqueTogether(
            name='projectcoursetopic',
            unique_together={('topic_id', 'topic_course')},
        ),
        migrations.AlterUniqueTogether(
            name='projectcourse',
            unique_together={('course_id', 'course_project')},
        ),
    ]
