# Generated by Django 2.1.2 on 2019-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_bg_image',
            field=models.CharField(default='bbb', max_length=50),
            preserve_default=False,
        ),
    ]
