# Generated by Django 2.1.2 on 2019-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_project_project_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_bg_image',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.TextField(max_length=500),
        ),
    ]
