# Generated by Django 2.1.2 on 2019-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20190102_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcourse',
            name='course_image',
            field=models.TextField(max_length=1000),
        ),
    ]
