# Generated by Django 2.1.2 on 2019-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20190122_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselabtask',
            name='lab_task_no',
            field=models.IntegerField(default=0),
        ),
    ]
