# Generated by Django 2.1.2 on 2019-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20190106_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselab',
            name='lab_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcourse',
            name='course_title',
            field=models.CharField(max_length=100),
        ),
    ]
