# Generated by Django 2.1.2 on 2019-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_userslabtaskstatus_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslabtaskstatus',
            name='status_id',
        ),
        migrations.AddField(
            model_name='projectcourse',
            name='lab_submission_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'submit by uploading document'), (2, 'submit by machine ID'), (3, 'submit from repo')], default=1),
        ),
        migrations.AlterField(
            model_name='courselabtask',
            name='lab_task_no',
            field=models.IntegerField(default=1),
        ),
    ]
