# Generated by Django 2.0.7 on 2019-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20190123_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_bg_image',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(null=True, upload_to='project'),
        ),
    ]
