# Generated by Django 2.0.7 on 2019-01-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20190131_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('project_id',), 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projectcourse',
            name='course_content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projectcourse',
            name='course_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projectcourse',
            name='course_image',
            field=models.ImageField(null=True, upload_to='project'),
        ),
    ]
