# Generated by Django 2.0.7 on 2019-01-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20190131_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcourse',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='projectcourse',
            unique_together={('course_id', 'course_project')},
        ),
    ]
