# Generated by Django 2.0.7 on 2019-02-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_auto_20190131_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcoursetopic',
            name='topic_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='projectcoursetopic',
            unique_together={('topic_id', 'topic_course')},
        ),
    ]
