# Generated by Django 2.1.2 on 2019-02-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_projectpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopicTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(unique=True)),
                ('task_no', models.IntegerField(default=1)),
                ('task', models.TextField()),
                ('task_note', models.TextField()),
                ('task_comment', models.TextField()),
                ('task_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectCourseTopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='courselab',
            name='lab_course',
        ),
        migrations.RemoveField(
            model_name='courselabtask',
            name='task_lab',
        ),
        migrations.RemoveField(
            model_name='userslabtaskstatus',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userslabtaskstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseLab',
        ),
        migrations.DeleteModel(
            name='CourseLabTask',
        ),
        migrations.DeleteModel(
            name='UsersLabTaskStatus',
        ),
    ]
