# Generated by Django 2.0.7 on 2019-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0014_auto_20190227_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_on_navigation',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
    ]
