# Generated by Django 2.1.2 on 2019-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_project',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.TextField(default='https://res.cloudinary.com/louiseyoma/image/upload/v1546701687/profile_pic.png'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pwd_reset_token',
            field=models.CharField(default='000011112222', max_length=100),
        ),
    ]
