# Generated by Django 2.1.2 on 2019-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pwd_reset_token',
            field=models.CharField(default='000011112222', max_length=100),
        ),
    ]
