# Generated by Django 2.0.7 on 2019-02-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190122_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allowed_project',
        ),
    ]
