# Generated by Django 2.1.2 on 2019-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_pwd_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_project',
            field=models.IntegerField(default=1),
        ),
    ]
