# Generated by Django 2.1.7 on 2019-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_username',
            field=models.CharField(default='defaultusername', max_length=100),
            preserve_default=False,
        ),
    ]
