# Generated by Django 2.0.7 on 2019-08-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_custom_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
