# Generated by Django 2.0.7 on 2019-12-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191213_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='number',
            new_name='role',
        ),
    ]
