# Generated by Django 2.0.7 on 2020-04-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awswebsocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=400)),
                ('the_type', models.CharField(default='plain', max_length=10)),
                ('timestamp', models.CharField(max_length=100, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qoute', to='awswebsocket.ChatMessageWithProfile')),
            ],
        ),
    ]
